### ISSUE TITLE
ValueError: too many values to unpack in python examples

### ISSUE THREAD

**Issue by alecomunian** [GAIA-UNIL/G2S#60]
Hello Mathieu! And thank you for sharing your code :-)

I tried all the scripts in the _example/python_ folder, and all of them give:

`ValueError: too many values to unpack`

the error is always located at the line where you collect the output of `g2s`, for example like in the script `unconditionalSimulation.py` at line 13.

`simulation, _ =g2s(...`

The error can be solved in all the scripts by changing `_` into `*_`, because in this way Python can throw away an undefined number of return values of `g2s` but the first argument.

This happens on Python 3.10.6.

Hope this helps.
Bests!

Alessandro

**Comment by mgravey** [comment]
Hi Alessandro,

You completely right, this changed with [3.10](https://docs.python.org/3/whatsnew/3.10.html#other-key-features).
@alecomunian, would you like to open a pull request?
Otherwise, @pauwiersma, if you have time, could you please fix the issue and double-check that everything works well?

If neither of you are available, I can take care of it next week when I have some free time.

Best regards,
Mathieu

**Comment by alecomunian** [comment]
Yes Mathieu, I will open a pull request ASAP.
Thank you and all the best!
Alessandro
